#!/bin/bash
# test-all.sh — run every suite in the repo plus the open-source guard.
#
# Usage: bash scripts/test-all.sh [--skip-node]
#
# Plain bash 3.2; every suite runs against committed synthetic fixtures — no
# live data, no network. The query suite and run-reachouts-readonly.sh need
# `node` (>= 22.6) and `npm ci` in packages/query/server; pass --skip-node
# (or lack node) to skip them. run-embeddings-tests.sh and
# run-gitignore-tests.sh run unconditionally (no node/Ollama required —
# embeddings tests use a deterministic fake-embed shim, no network).
# CI runs this exact script (.github/workflows/ci.yml).
set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

SKIP_NODE=0
[ "${1:-}" = "--skip-node" ] && SKIP_NODE=1

SUITES="
packages/core/tests/run-store-tests.sh
packages/core/tests/run-render-tests.sh
packages/core/tests/run-merge-tests.sh
packages/connectors/tests/run-capture-tests.sh
packages/connectors/tests/run-beeper-capture-tests.sh
packages/connectors/tests/run-beeper-out-tests.sh
packages/connectors/tests/run-deliver-tests.sh
packages/connectors/tests/run-scheduler-tests.sh
packages/ingestion/tests/run-seed-tests.sh
packages/ingestion/tests/run-triage-tests.sh
packages/ingestion/tests/run-shard-tests.sh
packages/ingestion/tests/run-structured-tests.sh
packages/ingestion/tests/run-scoring-tests.sh
packages/ingestion/tests/run-feedback-tests.sh
packages/ingestion/tests/run-thread-tests.sh
packages/ingestion/tests/run-refresh-tests.sh
packages/ingestion/tests/run-merge-candidates-tests.sh
packages/ingestion/tests/run-embeddings-tests.sh
packages/attention/tests/run-attention-tests.sh
packages/attention/tests/run-capacity-tests.sh
packages/attention/tests/run-queue-tests.sh
packages/attention/tests/run-staleness-tests.sh
packages/attention/tests/run-learn-tests.sh
packages/query/tests/run-who-next-direct-tests.sh
.claude/scripts/tests/run-oss-guard-tests.sh
.claude/scripts/tests/run-gitignore-tests.sh
.claude/scripts/oss-guard.sh
"

pass=0; fail=0; skip=0; failed=""
run() {
  local s="$1"
  if [ ! -f "$s" ]; then
    echo "SKIP  $s (not present)"; skip=$((skip+1)); return
  fi
  echo "=== $s"
  if bash "$s"; then pass=$((pass+1)); echo "PASS  $s"
  else fail=$((fail+1)); failed="$failed
  $s"; echo "FAIL  $s"; fi
}

for s in $SUITES; do run "$s"; done

# Private feedback eval suite (plan 34 D4) — generated by
# feedback-to-evals.sh from a user's own corrections, so it names real
# people and can never live in this public repo (packages/core/contracts/
# eval-case.md PII rule). ${RA_DATA_DIR:-data} matches this repo's
# convention (data/ gitignored, data/store the usual symlink into a
# private store — see data/README.md); run this only when that private
# manifest exists on disk, which it never does in CI, so CI always takes
# the SKIP branch below.
FEEDBACK_EVAL_SUITE="${RA_DATA_DIR:-data}/evals/feedback/suite.txt"
if [ -f "$FEEDBACK_EVAL_SUITE" ]; then
  FEEDBACK_EVAL_SUITE_ABS="$(cd "$(dirname "$FEEDBACK_EVAL_SUITE")" && pwd)/$(basename "$FEEDBACK_EVAL_SUITE")"
  echo "=== $FEEDBACK_EVAL_SUITE_ABS (private feedback eval suite)"
  if RA_EVAL_PRIVATE_MANIFEST="$FEEDBACK_EVAL_SUITE_ABS" RA_EVAL_DRY_RUN="${RA_EVAL_DRY_RUN:-1}" bash packages/core/scripts/eval-suite.sh "$FEEDBACK_EVAL_SUITE_ABS"; then
    pass=$((pass+1)); echo "PASS  $FEEDBACK_EVAL_SUITE_ABS"
  else
    fail=$((fail+1)); failed="$failed
  $FEEDBACK_EVAL_SUITE_ABS"; echo "FAIL  $FEEDBACK_EVAL_SUITE_ABS"
  fi
else
  echo "SKIP  private feedback eval suite (no $FEEDBACK_EVAL_SUITE)"; skip=$((skip+1))
fi

if [ "$SKIP_NODE" = 1 ] || ! command -v node >/dev/null 2>&1; then
  echo "SKIP  packages/query/tests/run-query-tests.sh (node unavailable or --skip-node)"; skip=$((skip+1))
else
  if [ ! -d packages/query/server/node_modules ]; then
    echo "--- npm ci (packages/query/server)"
    (cd packages/query/server && npm ci --silent) || { echo "FAIL  npm ci"; fail=$((fail+1)); }
  fi
  run packages/query/tests/run-query-tests.sh
  run packages/query/tests/run-reachouts-readonly.sh
fi

echo
echo "TOTAL: $pass passed, $fail failed, $skip skipped"
[ -n "$failed" ] && echo "FAILED:$failed"
[ "$fail" -eq 0 ]
